version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip npm
      - run: pip3 install -U pytest pytest-cov black flake8
      - run: npm install -g eslint htmlhint
      - checkout
      - run: pip3 install .
      # format and lint
      - run: LC_ALL=C.UTF-8 black --check setup.py tuna/ test/*.py
      - run: flake8 setup.py tuna/ test/*.py
      - run: eslint tuna/web/static/icicle.js
      - run: htmlhint tuna/web/index.html
      # Create a profile file
      - run: python3 -mcProfile -o test/foo.prof test/foo.py
      # The tests
      - run: cd test/ && pytest --cov tuna
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash) -R ~/work
