version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo apt install -y npm
      - run: pip3 install -U black flake8 --user
      - run: npm install -g eslint htmlhint
      # format and lint
      - run: black --check .
      - run: flake8 .
      - run: eslint tuna/web/static/icicle.js
      - run: htmlhint tuna/web/index.html
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run: pip3 install . --user
      # Create a profile file
      - run: python3 -mcProfile -o test/foo.prof test/foo.py
      # The tests
      - run: 
          command: pytest --cov tuna
          working_directory: test/
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
