name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .
    - name: Lint with npm
      run: |
        npm run prettier
        npm run htmlhint
    # May 2020: htmlhint broken: SyntaxError: Unexpected token return
    # - name: Lint with htmlhint
    #   run: |
    #     npm install -g htmlhint
    #     htmlhint tuna/web/index.html

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Test with tox
      run: |
        pip install tox
        tox
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.9' }}
